// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE3_Evra6LM0Z0hR9Im1I_mAv3h7wRjV4',
    appId: '1:399218268680:android:45c00bc2c2356477590fbd',
    messagingSenderId: '399218268680',
    projectId: 'fluxstore-97f24',
    databaseURL: 'https://fluxstore-97f24-default-rtdb.firebaseio.com',
    storageBucket: 'fluxstore-97f24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo4Pjs7f_fwcEi6gKhoPN-aQp-UwoJ2Ls',
    appId: '1:399218268680:ios:c487301ad15a721d590fbd',
    messagingSenderId: '399218268680',
    projectId: 'fluxstore-97f24',
    databaseURL: 'https://fluxstore-97f24-default-rtdb.firebaseio.com',
    storageBucket: 'fluxstore-97f24.appspot.com',
    androidClientId: '399218268680-llc0vqb874k84ubf2k9ido0vheh1klis.apps.googleusercontent.com',
    iosClientId: '399218268680-71rt98galeqoob7h8tksn8n1cfese8qi.apps.googleusercontent.com',
    iosBundleId: 'com.example.todotask.todoTask',
  );
}
